# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Milad Vazan
title: Deep Learning Researcher
email: vazanmilad@gmail.com
website: mr-relu.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: milad_vazan
github_username:  milad-ai
# stackoverflow_username: "00000001"
instagram_username: vazanmilad
linkedin_username: miladvazan

# orcid_username: 0000-0002-4008-7820

# Additional icon links
additional_links:
- title: Milad Vazan
  icon: fas fa-globe
  url: https://www.miladvazan.ir
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/p.jpg
about_content: | # this will include new lines to allow paragraphs
  
  Milad Vazan is a dedicated <mark>deep learning researcher</mark> and <mark>author</mark>, specializing in Soft Computing and Artificial Intelligence. With a Bachelor's Degree in Computer Engineering (Software) and a Master's Degree in Computer Science, his research efforts are focused on developing robust neural network architectures and efficient training algorithms. Milad has also authored valuable books in <mark>Persian</mark> on deep learning and machine learning, catering to the needs of Persian-speaking readers.


content:

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title:  Shahid Beheshti University (SBU)
        caption: 2023 - 2027
        sub_title: Ph.D. Student
        quote: >
         Soft computing and artificial intelligence
        description: | # this will include new lines to allow paragraphs
          
      - layout: left  
        title: University of Tabriz
        caption: 2018 - 2020
        sub_title: MASTER DEGREE OF COMPUTER SCIENCE
        quote: >
         Soft computing and artificial intelligence
        description: |
          THESIS: sentiment analysis of social media users for opinions polarity detection using deep learning techniques.
  - title: Skills
    layout: list
    content:
      - PyTorch
      - Keras


footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
